import stats 

stats = stats.Stats()

list1 = [1,3,5,6]
list2 = [1,3,4,5]

total1 = stats.total(list1)  
total2 = stats.total(list2)  
mean1 = stats.mean(list1)  
mean2 = stats.mean(list2)  
mode1 = stats.mode(list1)  
mode2 = stats.mode(list2)  
median1 = stats.median(list1)  
median2 = stats.median(list2)  
variance1 = stats.variance(list1)  
variance2 = stats.variance(list2)  
standard_deviation1 = stats.SD(list1)  
standard_deviation2 = stats.SD(list2)  
covariance_pop = stats.covariance(list1, list2)  
covariance_sample = stats.covariance(list1, list2, True)  
correlation = stats.correlation(list1, list2)  
skewness_pop1 = stats.skewness(list1)  
skewness_pop2 = stats.skewness(list2)  
skewness_sample1 = stats.skewness(list1, True)  
skewness_sample2 = stats.skewness(list2, True)  
kurtosis_pop1 = stats.kurtosis(list1)  
kurtosis_pop2 = stats.kurtosis(list2)  
kurtosis_sample1 = stats.kurtosis(list1, True)  
kurtosis_sample2 = stats.kurtosis(list2, True)  

print("Total1:", total1)
print("Total2:", total2)
print("Mean1:", mean1)
print("Mean2", mean2)
print("Mode1:", mode1)
print("Mode2:", mode2)
print("Median1:", median1)
print("Median2:", median2)
print("Variance1:", variance1)
print("Variance2:", variance2)
print("Standard Deviation1:", standard_deviation1)
print("Standard Deviation2:", standard_deviation2)
print("Covariance (Population):", covariance_pop)
print("Covariance (Sample):", covariance_sample)
print("Correlation (Population):", correlation)
print("SkewnessPop1 (Population):", skewness_pop1)
print("SkewnessPop2 (Population):", skewness_pop2)
print("SkewnessSample1 (Sample):", skewness_sample1)
print("SkewnessSample2 (Sample):", skewness_sample2)
print("Kurtosis1 (Population):", kurtosis_pop1)
print("Kurtosis2 (Population):", kurtosis_pop2)
print("Kurtosis1 (Sample):", kurtosis_sample1)
print("Kurtosis2 (Sample):", kurtosis_sample2)

